travis:
  secure:
    BINSTAR_TOKEN: YJxLQ0ltCKQaGRuAPmyiMWgYZa4wPgBUJoO+FhEIWq8qseZJGKdpYYC5jvJ+JlwA/Y3tkG1fzTqHmgBWCsb7PsDD9RiUuYitn3mf9YDYjZI0FJirCWgTbB7Wb1Sr+5p13qoITkEgwdJXYq/D2b84ovU6xTM3GnJ/LKX/qexbncihfsUGMZDCJycfYCH4T3jFWerhMofiyK7Ag9hJuq4gHZRqupoF28hmLPCLyJ9+q8P8dF1MKdwIsgDt6HKHlaJgJsbnmp4Ai5C4Fc8X/o4GTynfJ3Meere4KxnYdvtZyoPGdQjqm5gJj+NPb1zQxwlmfxUvucheJtvG+motzDtleM+X+PBlql1yom1MR93HgdzC10Ll2aAxka3hd+Ly84LcwHXKDo1HbJvFoYdgz7N2+Lridshij49oMSxMGUOQgiGlsg8D/rhMDRG2hbl70D0x6MMp7OY9vz88ctmdr1KE5ZywCg0TA+xIrVYr1LFyMHtYDWq6lHUM3uXTS2VbVbeWtuWhcXslpMXtBYK6EFT6SvSElBaK2ix34z3aUeBQXIbW1j1Ruphnia7rEJqhhmFRTUbFSgd9rmJvYU2mDEdx+IccMoJFfytNBke+NJnuMo5kL8PVL9e0W/w9N7swb95VmRZ4IfcJSJEvjmW+u/Iy/v3qLFPDHJvM3UL56Gy6Cts=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
