travis:
  secure:
    BINSTAR_TOKEN: vWLc16boHmVDOwtS2+43LOMPSKRGm36d794Oei9daTR2vc59flGbMDWyE/BqXUOP6mDLzjzuR3jW15J0QjiaKVlriESGNSc4YAqdJspuGiWKdm5cPDZhFlNFsDE92WesXZaOMtESGON98al4Q1MiSG0pzyVjxghpUXfJykN+5BofDkNrwU/B948zTP5fR143R5iTDyWDqm/AUjBzsMYjuIV9dy8HblETXXOro7CaxdVR7NBQJ8vYsd+zBTPHiYWzgJJSjwAZUyLyoe0GF/UwM2QBDhQfudHEYfgye22n7CqQUSORcmh/1bafEk8Dew/oj8GDFuBaUEhmL5SoEvTD4inoxqeaaU4EO1U320MfFjKTudF9+HGGsuGpusmfL/9Tcim3WqEU0vbZ3Jm1Qt+AQGcT1qvvsMqdJhInYB9PZwNQTSyRs3mt+kxCakuQiWKWw2tlpy9HDnq+vn3WXK71KBYJYNc0GNVdnz7Db1gMaJGWPAECcVW9WvvjXPT8kktVMFC9L4r2q3oyAJ3mfUUWC6u3YRUuDwUxmXJg+tp7TAgSV7HVlkabV1rJdUj6nt3KOn+TdLS6UBucLNcJdiT4XcW1sFXvirtGgf4thqowgbgQC4+4WrgF1otTyj4uThXWQSNNsMK8j9iJoqG1ZkMwKvLEM/GQQr8GleJVp0SN4yA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
